[package]
name = "rust_orm_lib"
version = "0.1.0"
authors = ["Alayna Richmond <richmond.alayna@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = "1.0.5"
